version: '3.8'
services:
  app:
    image: icesmart
    container_name: api-icesmart-container
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

  # postgres:
  #  image: postgres:latest
  #  container_name: postgres-api-seller
  # environment:
  #   POSTGRES_USER: ${POSTGRES_USER}
  #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   POSTGRES_DB: ${POSTGRES_DB}
  # ports:
  #   - "5432:5432"
  # networks:
  #   - app-network

networks:
  app-network:
    driver: bridge


