spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://ep-lucky-night-a8t4vse9-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_2jfvKEJ3WGNU
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

server:
  port: 8081 #set your port

wiza:
  api:
    url: ${WIZA_API_URL}
    token: ${AUTH_TOKEN}



  # Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  swagger-ui:
    path: /docs-seller-api.html
  api-docs:
    path: /docs-seller-api
  packagesToScan: com.masprogtech.controllers